[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate_schemas --shared && python manage.py collectstatic --noinput && gunicorn accesswash_platform.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10