# Generated by Django 5.1.9 on 2025-06-10 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='For hierarchical assets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assets', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='assetinspection',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='assetinspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetinspection',
            name='photos',
            field=models.ManyToManyField(blank=True, to='distro.assetphoto'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distro.assettype'),
        ),
        migrations.AddField(
            model_name='meter',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_details', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipe_details', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='end_node',
            field=models.ForeignKey(blank=True, help_text='Asset at pipe end', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_pipes', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='start_node',
            field=models.ForeignKey(blank=True, help_text='Asset at pipe start', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_pipes', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='valve',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valve_details', to='distro.asset'),
        ),
        migrations.AddField(
            model_name='valve',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distro.zone'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_id'], name='assets_asset_i_6c35ce_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='assets_asset_t_92caec_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['zone'], name='assets_zone_id_6c9889_idx'),
        ),
    ]
