# Generated by Django 5.1.9 on 2025-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='utility_logos/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('distro_enabled', models.BooleanField(default=True)),
                ('huduma_enabled', models.BooleanField(default=False)),
                ('maji_enabled', models.BooleanField(default=False)),
                ('hesabu_enabled', models.BooleanField(default=False)),
                ('ripoti_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility Settings',
                'verbose_name_plural': 'Utility Settings',
                'db_table': 'core_utility_settings',
            },
        ),
    ]
