# Generated by Django 5.1.9 on 2025-07-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitysettings',
            name='utility',
            field=models.OneToOneField(blank=True, help_text='The utility this settings belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.utility'),
        ),
    ]
